{% set name = "jobard-client" %}
{% set version = "1.6.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/jobard/jobard_client/-/archive/{{ version }}/jobard_client-{{ version }}.tar.gz
  sha256: 1c6f4d4abbf2a568020b136273a3a04dbd803c758620270497845209589930d2

build:
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - jobard-client = jobard_client.cli.application:main

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >={{ python_min }}
    - requests >=2.32.3
    - pydantic >=2.9,<3.0

test:
  imports:
    - jobard_client

about:
  home: https://gitlab.ifremer.fr/jobard/jobard_client
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Python client for Job Array Daemon.


extra:
  recipe-maintainers:
    - marie59
    - criou-cg
