{% set name = "jobard-client" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/jobard/jobard_client/-/archive/{{ version }}/jobard_client-{{ version }}.tar.gz
  sha256: 39df8683b04f920f21cd8cb900326b2551c0668512f293a96b06e79a2435861f

build:
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - jobard-client = jobard_client.cli.application:main

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >=3.8
    - requests >=2.26.0,<2.30
    - pydantic >=1.8.2,<1.9
    - click >=8.0.2
    - tabulate >=0.8.9,<0.9
    - pandas >=1.5,<2.0

test:
  imports:
    - jobard_client

about:
  home: https://gitlab.ifremer.fr/jobard/jobard_client
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Python client for Job Array Daemon.


extra:
  recipe-maintainers:
    - marie59
    - criou-cg
